### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by drewroberts** [tipoff/laravel-serpapi#4]
What can we do to get this package to be compatible with PHP 8?

**Comment by drewroberts** [comment]
https://github.com/serpapi/google-search-results-php/issues/7

**Comment by drewroberts** [comment]
Would it be better to just take the SerpApi code and move it into this package so we can allow PHP 8?

**Comment by kylebarney** [comment]
Looks like this is resolved. Can we close this issue out, @drewroberts ?

**Comment by drewroberts** [comment]
Tes, thank you.
