### ISSUE TITLE
SerpApiSearchException causes fatal PHP exceptions

### ISSUE THREAD

**Issue by chx2** [tipoff/laravel-serpapi#5]
Currently, this package will trigger fatal PHP Execution errors. This is due to the `SerpApiSearchException` being instantiated within the `SerpApiSearch` package class. I think it may make better sense to refactor the exception into a separate file.

<img width="954" alt="Screen Shot 2021-02-27 at 1 33 11 PM" src="https://user-images.githubusercontent.com/24723492/109398128-56e8f280-7900-11eb-9e62-74793c11df0c.png">

**Comment by arwaawan3** [comment]
@drewroberts @chx2 If this is resolved, can we close this issue?

**Comment by chx2** [comment]
@arwaawan3 thanks!
